"""expand candidate profile

Revision ID: 005_expand_candidate_profile
Revises: 004_add_applied_job_title
Create Date: 2026-03-18 07:42:23.887197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_expand_candidate_profile'
down_revision: Union[str, None] = '004_add_applied_job_title'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('experience_years', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('notice_period_days', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('current_ctc', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('expected_ctc', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('work_mode_preference', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('availability_status', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('interview_availability_days', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('interview_time_slot', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('blackout_dates', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('weekend_interviews', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'weekend_interviews')
    op.drop_column('candidates', 'blackout_dates')
    op.drop_column('candidates', 'interview_time_slot')
    op.drop_column('candidates', 'interview_availability_days')
    op.drop_column('candidates', 'availability_status')
    op.drop_column('candidates', 'work_mode_preference')
    op.drop_column('candidates', 'expected_ctc')
    op.drop_column('candidates', 'current_ctc')
    op.drop_column('candidates', 'notice_period_days')
    op.drop_column('candidates', 'experience_years')
    # ### end Alembic commands ###
