"""
Offer letter PDF generation using WeasyPrint.
"""
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


OFFER_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  @page {{ margin: 2.5cm 2cm; }}
  body {{ font-family: Helvetica, Arial, sans-serif; font-size: 11pt; color: #1a1a1a; line-height: 1.5; margin: 0; padding: 0; }}

  .header {{ text-align: center; border-bottom: 3px solid #7c3aed; padding-bottom: 14px; margin-bottom: 20px; }}
  .company-name {{ font-size: 22pt; font-weight: bold; color: #7c3aed; margin: 0 0 4px 0; }}
  .doc-title {{ font-size: 13pt; color: #4b5563; margin: 0; }}

  .meta-row {{ width: 100%; margin-bottom: 16px; }}
  .meta-date {{ text-align: right; color: #6b7280; font-size: 10pt; }}

  .candidate-block {{ margin-bottom: 14px; }}
  .candidate-block strong {{ font-size: 12pt; }}

  p {{ margin: 0 0 10px 0; font-size: 11pt; }}

  h2 {{ font-size: 11pt; font-weight: bold; color: #7c3aed; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 18px 0 8px 0; }}

  .comp-table {{ width: 100%; border-collapse: collapse; margin: 0 0 14px 0; }}
  .comp-table td {{ padding: 7px 10px; border: 1px solid #e5e7eb; font-size: 10.5pt; vertical-align: top; }}
  .comp-table td.label {{ font-weight: bold; background: #f9fafb; width: 38%; }}

  .contingency {{ margin: 16px 0; font-size: 10pt; color: #374151; }}

  .sig-table {{ width: 100%; border-collapse: collapse; margin-top: 24px; }}
  .sig-table td {{ width: 50%; padding: 0 10px; vertical-align: bottom; }}
  .sig-table td:first-child {{ padding-left: 0; }}
  .sig-table td:last-child {{ padding-right: 0; text-align: right; }}
  .sig-line {{ border-top: 1px solid #1a1a1a; padding-top: 4px; font-size: 10pt; color: #374151; }}

  .footer {{ margin-top: 20px; border-top: 1px solid #e5e7eb; padding-top: 8px; color: #9ca3af; font-size: 9pt; text-align: center; }}
</style>
</head>
<body>

  <div class="header">
    <p class="company-name">{company_name}</p>
    <p class="doc-title">Offer of Employment</p>
  </div>

  <table class="meta-row"><tr><td class="meta-date">{offer_date}</td></tr></table>

  <div class="candidate-block">
    <strong>{candidate_name}</strong><br>
    {candidate_email}
  </div>

  <p>Dear {candidate_name},</p>
  <p>We are pleased to offer you the position of <strong>{position_title}</strong> at <strong>{company_name}</strong>. We look forward to having you join our team.</p>

  <h2>Compensation &amp; Benefits</h2>
  <table class="comp-table">
    <tr><td class="label">Position</td><td>{position_title}</td></tr>
    <tr><td class="label">Base Salary</td><td>{salary_currency} {base_salary:,.0f} per annum</td></tr>
    {bonus_row}
    {equity_row}
    {start_date_row}
    {expiry_row}
  </table>

  {benefits_section}

  {custom_content}

  <p class="contingency">This offer is contingent upon successful completion of background verification. Please sign and return this letter by the expiry date to indicate your acceptance.</p>

  <table class="sig-table">
    <tr>
      <td>
        <div class="sig-line">
          Authorized Signatory &mdash; {company_name}
        </div>
      </td>
      <td>
        <div class="sig-line">
          Candidate Acceptance &mdash; {candidate_name}
        </div>
      </td>
    </tr>
  </table>

  <div class="footer">
    Generated by HireOn &bull; Confidential &mdash; for recipient only
  </div>

</body>
</html>
"""


def generate_offer_html(
    company_name: str,
    candidate_name: str,
    candidate_email: str,
    position_title: str,
    base_salary: float,
    salary_currency: str,
    bonus: float | None,
    equity: str | None,
    benefits: str | None,
    start_date: datetime | None,
    expiry_date: datetime | None,
    letter_content: str | None,
) -> str:
    """Build HTML for the offer letter."""
    offer_date = datetime.now().strftime("%B %d, %Y")
    bonus_row = f"<tr><td>Bonus</td><td>{salary_currency} {bonus:,.0f}</td></tr>" if bonus else ""
    equity_row = f"<tr><td>Equity</td><td>{equity}</td></tr>" if equity else ""
    start_date_row = f"<tr><td>Start Date</td><td>{start_date.strftime('%B %d, %Y')}</td></tr>" if start_date else ""
    expiry_row = f"<tr><td>Offer Expires</td><td>{expiry_date.strftime('%B %d, %Y')}</td></tr>" if expiry_date else ""
    benefits_section = f"<h2>Benefits</h2><p>{benefits}</p>" if benefits else ""
    custom_content = f"<h2>Additional Terms</h2><p>{letter_content}</p>" if letter_content else ""

    return OFFER_HTML_TEMPLATE.format(
        company_name=company_name,
        offer_date=offer_date,
        candidate_name=candidate_name,
        candidate_email=candidate_email,
        position_title=position_title,
        salary_currency=salary_currency,
        base_salary=base_salary,
        bonus_row=bonus_row,
        equity_row=equity_row,
        start_date_row=start_date_row,
        expiry_row=expiry_row,
        benefits_section=benefits_section,
        custom_content=custom_content,
    )


async def generate_offer_pdf(html_content: str) -> bytes:
    """Convert HTML offer letter to PDF bytes using xhtml2pdf."""
    try:
        import io
        from xhtml2pdf import pisa

        buf = io.BytesIO()
        result = pisa.CreatePDF(html_content, dest=buf)
        if result.err:
            raise RuntimeError(f"xhtml2pdf error code: {result.err}")
        return buf.getvalue()
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        raise
